<span style="font-size: 1.75em;font-weight: bold;">Documents</span>
<br/><br/>

<?php if($block->isEnable()): ?>
    <?php $dbn=array("Protocol","MSDS","QC","Other"); ?>
    <?php foreach ($dbn as $val) :?>
        <?php $documents = $block->getDocument($val); ?>
        <?php if(!empty($documents) && sizeof($documents) > 0): ?>
            <span style='font-size: 1em;font-weight: normal;text-align:left;width:160px;text-transform:none;'>
                <?php
                    if($val == 'Protocol'){
                        echo "<i>Supporting Protocol</i>";
                    }else{
                        echo "<i>".$val."</i>";
                    }
                ?>
            </span>
            <ul style='margin-bottom:10px;'>
                <?php foreach ($documents as $document):?>
                    <li>
                        <a href="<?php  echo $block->getDocumentUrl($document->getUrl()); ?>" target="_blank">
                            <div class="documentment-icon" style="float: left;padding-left: 130px;padding-right: 10px;">
                                <img src="<?php  echo $block->getFileIcon($document->getFiletype()) ?>"; />
                            </div>
                            <?php echo $document->getName(); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <br/>
        <?php endif; ?>
    <?php endforeach; ?>


<?php endif; ?>